# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c57e4237b0bb5d4015a82831947a91b48cce4f3537eebf104cfdd0996d3266526591d6a354758025bb2fc5bb2aa1232b94efdc21c2e0ff3c9cf5654b5fe5f2c6

test:
  secret_key_base: f274241437fb62937c7daa3b490c2255523a48467ae3a99188d308bd033c77b2d09863e4cfe5a3b6c47cda52b323258518ad97bb49581873f1851df8a1f83588

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
